[package]
name = "json-glue"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.219"
serde-wasm-bindgen = "0.6.5"
serde_json = "1.0.140"
wasm-bindgen = "0.2.100"

[lib]
crate-type = ["cdylib"]
